apiVersion: apps/v1
kind: Deployment
metadata:
  name: coding-task
spec:
  selector:
    matchLabels:
      run: coding-task
  replicas: 1
  template:
    metadata:
      labels:
        run: coding-task
    spec:
      containers:
      - name: coding-task
        image: sunsniffercontainer.azurecr.io/billing-service:dev-latest
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: acr-auth

---
apiVersion: v1
kind: Service
metadata:
 name: coding-task
spec:
 ports:
 - name: "www"
   port: 3000
   targetPort: 3000
 selector:
  run: coding-task

