version: '3.9'
services:
  db:
    image: 'mongo'
    volumes:
      - './data/mongo:/data/db'
    ports:
      - 27017:27017
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    command: mongod --logpath=/dev/null
    restart: always
